#!/usr/bin/env node
// Generate STATUS.md from the current state of web_sketches/ and processing_sketches/.
// Re-run any time you port or move a sketch.

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const WEB = path.join(ROOT, 'web_sketches');
const PROC = path.join(ROOT, 'processing_sketches');
const OUT = path.join(ROOT, 'STATUS.md');
const TOTAL_DAYS = 365;

function leadingDay(name) {
  // strip optional "sketch_" prefix; parse leading digits
  const stripped = name.replace(/^sketch_/, '');
  const m = stripped.match(/^(\d+)/);
  return m ? parseInt(m[1], 10) : null;
}

function readDirSafe(p) {
  try {
    return fs
      .readdirSync(p, { withFileTypes: true })
      .filter((d) => d.isDirectory() && d.name !== 'libraries' && !d.name.startsWith('_'))
      .map((d) => d.name);
  } catch {
    return [];
  }
}

function groupByDay(names) {
  const byDay = new Map();
  for (const name of names) {
    const day = leadingDay(name);
    if (day == null) continue;
    if (!byDay.has(day)) byDay.set(day, []);
    byDay.get(day).push(name);
  }
  return byDay;
}

const webNames = readDirSafe(WEB).filter((n) =>
  fs.existsSync(path.join(WEB, n, 'index.html'))
);
const procNames = readDirSafe(PROC);

const webByDay = groupByDay(webNames);
const procByDay = groupByDay(procNames);

const lines = [];
const counts = { live: 0, multiple: 0, processing: 0, missing: 0 };

for (let d = 1; d <= TOTAL_DAYS; d++) {
  const web = webByDay.get(d) || [];
  const proc = procByDay.get(d) || [];

  if (web.length === 1) {
    lines.push(`✅${d}`);
    counts.live++;
  } else if (web.length > 1) {
    lines.push(`[ ]${d} - multiple sketches (${web.join(', ')})`);
    counts.multiple++;
  } else if (proc.length > 0) {
    const label = proc.length === 1 ? proc[0] : `${proc.length} variants: ${proc.join(', ')}`;
    lines.push(`[ ]${d} - Processing (${label})`);
    counts.processing++;
  } else {
    lines.push(`[ ]${d} - missing`);
    counts.missing++;
  }
}

const header = `# Sketch Status

Daily progress on the 365-- project. The goal was 365 sketches; some days were
spent in Unity (not represented here) and some web sketches have multiple
variants.

**Legend**
- ✅ — single sketch live in the gallery (\`web_sketches/\`)
- \`[ ]\` — needs attention:
  - \`Processing\` — exists in \`processing_sketches/\`, not yet ported
  - \`multiple sketches\` — several variants exist for this day; pick or consolidate
  - \`missing\` — no sketch for this day (likely Unity work or skipped)

**Totals**: ${counts.live} live · ${counts.multiple} multi · ${counts.processing} Processing-only · ${counts.missing} missing
*(Generated by \`node scripts/build-status.js\` — re-run after porting / moving sketches.)*

---

`;

fs.writeFileSync(OUT, header + lines.join('\n') + '\n');
console.log(`Wrote ${path.relative(ROOT, OUT)}: ${counts.live} live, ${counts.multiple} multi, ${counts.processing} Processing, ${counts.missing} missing`);
